# Generated by Django 5.0.1 on 2025-12-19 23:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                ("total_bookings", models.IntegerField(default=0)),
                ("confirmed_bookings", models.IntegerField(default=0)),
                ("cancelled_bookings", models.IntegerField(default=0)),
                ("total_tickets_sold", models.IntegerField(default=0)),
                ("total_tickets_checked_in", models.IntegerField(default=0)),
                ("gross_revenue", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("net_revenue", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "discounts_given",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("mpesa_revenue", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("card_revenue", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("ticket_type_sales", models.JSONField(blank=True, default=dict)),
                ("promo_codes_used", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Event Analytics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["event", "date"], name="analytics_e_event_i_ae3505_idx"),
                    models.Index(fields=["date"], name="analytics_e_date_59a50a_idx"),
                ],
                "unique_together": {("event", "date")},
            },
        ),
        migrations.CreateModel(
            name="OrganizerAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("month", models.DateField()),
                ("total_events", models.IntegerField(default=0)),
                ("active_events", models.IntegerField(default=0)),
                ("completed_events", models.IntegerField(default=0)),
                ("cancelled_events", models.IntegerField(default=0)),
                ("total_bookings", models.IntegerField(default=0)),
                ("total_tickets_sold", models.IntegerField(default=0)),
                ("total_revenue", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "avg_ticket_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "avg_tickets_per_event",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        limit_choices_to={"role": "ORGANIZER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Organizer Analytics",
                "ordering": ["-month"],
                "indexes": [
                    models.Index(
                        fields=["organizer", "month"], name="analytics_o_organiz_ba6551_idx"
                    )
                ],
                "unique_together": {("organizer", "month")},
            },
        ),
    ]
