# Generated by Django 5.0.1 on 2025-12-26 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
        ("events", "0001_initial"),
        ("users", "0004_attendee_wallettransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="attendee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="users.attendee",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("MPESA", "M-Pesa"), ("CARD", "Card Payment"), ("WALLET", "Wallet")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["attendee", "created_at"], name="bookings_bo_attende_e314c9_idx"
            ),
        ),
    ]
