# Generated by Django 5.0.1 on 2026-08-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_booking_attendee_alter_booking_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MPESA", "M-Pesa"),
                    ("CARD", "Card Payment"),
                    ("WALLET", "Wallet"),
                    ("CASH", "Cash"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
