[pytest]
DJANGO_SETTINGS_MODULE = config.settings.development
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
addopts =
    --reuse-db
    --cov=apps
    --cov-report=html
    --cov-report=term-missing
    -v
    --ignore=test_auth.py
    --ignore=test_password_reset.py
    --ignore=test_attendee_emails.py
