# Generated by Django 5.0.1 on 2025-12-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_attendee_wallettransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="password",
            field=models.CharField(default="", max_length=128),
        ),
    ]
