# Generated by Django 5.0.1 on 2025-12-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_attendee_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
