# Generated by Django 5.0.1 on 2025-12-26 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_attendee_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="attendee",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendee",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True, verbose_name="last login"),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
