# Generated by Django 5.0.1 on 2025-12-26 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_attendee_date_joined_attendee_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="attendee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verifications",
                to="users.attendee",
            ),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(fields=["attendee", "used"], name="users_email_attende_a392af_idx"),
        ),
        migrations.AddConstraint(
            model_name="emailverification",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("attendee__isnull", True), ("user__isnull", False)),
                    models.Q(("attendee__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="email_verification_user_xor_attendee",
            ),
        ),
    ]
