# Generated by Django 5.0.1 on 2025-12-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_emailverification_attendee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="balance_after",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
