# Generated by Django 5.0.1 on 2025-12-27 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_add_balance_after_to_wallet_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordreset",
            name="attendee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_resets",
                to="users.attendee",
            ),
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_resets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="passwordreset",
            index=models.Index(fields=["attendee", "used"], name="users_passw_attende_f56721_idx"),
        ),
        migrations.AddConstraint(
            model_name="passwordreset",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("attendee__isnull", True), ("user__isnull", False)),
                    models.Q(("attendee__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="password_reset_user_or_attendee",
            ),
        ),
    ]
