# Generated by Django 5.0.1 on 2025-12-28 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettype",
            name="max_purchase",
            field=models.IntegerField(
                default=10,
                help_text="Maximum number of tickets per order",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tickettype",
            name="min_purchase",
            field=models.IntegerField(
                default=1,
                help_text="Minimum number of tickets per order",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
