# Generated by Django 5.0.1 on 2025-12-19 15:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("booking_reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("MPESA", "M-Pesa"), ("CARD", "Card Payment")],
                        default="MPESA",
                        max_length=20,
                    ),
                ),
                ("mpesa_receipt_number", models.CharField(blank=True, max_length=100, null=True)),
                ("checkout_request_id", models.CharField(blank=True, max_length=100, null=True)),
                ("merchant_request_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("transaction_reference", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("result_code", models.CharField(blank=True, max_length=10, null=True)),
                ("result_description", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_reference"], name="payments_tr_transac_87d35e_idx"
                    ),
                    models.Index(
                        fields=["checkout_request_id"], name="payments_tr_checkou_34e8a5_idx"
                    ),
                    models.Index(
                        fields=["phone_number", "created_at"], name="payments_tr_phone_n_df8451_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="payments_tr_status_e3597b_idx"
                    ),
                ],
            },
        ),
    ]
