# Generated by Django 5.0.1 on 2025-12-26 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("payments", "0003_setup_periodic_tasks"),
        ("users", "0008_emailverification_attendee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="attendee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_transactions",
                to="users.attendee",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="events.event",
            ),
        ),
    ]
