# Generated by Django 5.0.1 on 2025-12-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_transaction_attendee_alter_transaction_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
