# Generated by Django 5.0.1 on 2026-08-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_make_phone_number_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[("MPESA", "M-Pesa"), ("CARD", "Card Payment"), ("CASH", "Cash")],
                default="MPESA",
                max_length=20,
            ),
        ),
    ]
